/*
===========================================================
EDA Phase 05 - Magnitude Analysis
===========================================================

Purpose:
Analyze the size, volume, and revenue impact across various business dimensions, including geography, gender, product categories, and customer segments.

What It Does:
- Counts total customers by country and gender
- Counts total products by category
- Calculates average product cost per category
- Aggregates total revenue by category and customer
- Analyzes the distribution of items sold across countries

SQL Functions Used:
- COUNT(), SUM(), AVG()
- GROUP BY, ORDER BY
- LEFT JOIN

===========================================================
*/

-- Total customers by country
SELECT country,
       COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;
GO

-- Total customers by gender
SELECT gender,
       COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;
GO

-- Total products by category
SELECT category,
       COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;
GO

-- Average product cost by category
SELECT category,
       AVG(cost) AS average_costs
FROM gold.dim_products
GROUP BY category
ORDER BY average_costs DESC;
GO

-- Total revenue by product category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
GO

-- Total revenue generated by each customer
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;
GO

-- Total items sold across countries
SELECT 
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
GO

